export enum Sentinela {
  nivel1 = ``,
  nivel2 = ``,
  nivel3 = ``,
  nivel4 = ``,
  nivel5 = ``,
  nivel6 = ``,
  nivel7 = ``,
  nivel8 = ``,
  nivel9 = ``,
  nivel10 = ``,
}
export enum Sussurro {
  nivel1 = ``,
  nivel2 = ``,
  nivel3 = ``,
  nivel4 = ``,
  nivel5 = ``,
  nivel6 = ``,
  nivel7 = ``,
  nivel8 = ``,
  nivel9 = ``,
  nivel10 = ``,
}
export enum Sombrio {
  nivel1 = ``,
  nivel2 = ``,
  nivel3 = ``,
  nivel4 = ``,
  nivel5 = ``,
  nivel6 = ``,
  nivel7 = ``,
  nivel8 = ``,
  nivel9 = ``,
  nivel10 = ``,
}
